spring:
  webflux:
    base-path: /reactive-flashcards
  data:
    mongodb:
      uri: mongodb://reactive-flashcards:reactive-flashcards@localhost:27017/reactive-flashcards?authSource=admin
  mail:
    host: mailcatcher
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25


reactive-flashcards:
  mail:
    sender: Reactive Flashcards <noreply@reactiveflashcards.com.br>

retry-config:
  max-retries: 3
  min-duration: 1

http-client:
  response-timeout:
  read-timeout:

deck-api:
  base-url: http://localhost:3030
  auth-response: auth
  decks-resource: decks
